---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-customize-deploy.html 
keywords: deploy, trident, methods, operator, tridentctl, helm, attributes, customize, tridentorchestrator 
summary: 'L"operatore Trident consente di personalizzare il modo in cui Astra Trident viene installato utilizzando gli attributi in `TridentOrchestrator` spec.' 
---
= Personalizzare l'implementazione dell'operatore Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


L'operatore Trident consente di personalizzare il modo in cui Astra Trident viene installato utilizzando gli attributi in `TridentOrchestrator` spec.

Per un elenco degli attributi, consultare la tabella seguente:

[cols="3"]
|===
| Parametro | Descrizione | Predefinito 


| `namespace` | Spazio dei nomi in cui installare Astra Trident | "predefinito" 


| `debug` | Attiva il debug per Astra Trident | falso 


| `IPv6` | Installare Astra Trident su IPv6 | falso 


| `k8sTimeout` | Timeout per le operazioni Kubernetes | 30 sec 


| `silenceAutosupport` | Non inviare pacchetti AutoSupport automaticamente a NetApp | falso 


| `enableNodePrep` | Gestire automaticamente le dipendenze dei nodi di lavoro (*BETA*) | falso 


| `autosupportImage` | L'immagine del contenitore per la telemetria AutoSupport | "netapp/trident-autosupport:21.04.0" 


| `autosupportProxy` | Indirizzo/porta di un proxy per l'invio di telemetria AutoSupport | "http://proxy.example.com:8888"[] 


| `uninstall` | Flag utilizzato per disinstallare Astra Trident | falso 


| `logFormat` | Formato di registrazione Astra Trident da utilizzare [text,json] | "testo" 


| `tridentImage` | Immagine Astra Trident da installare | "netapp/trident:21.04" 


| `imageRegistry` | Percorso al registro interno, del formato
`<registry FQDN>[:port][/subpath]` | "k8s.gcr.io/sig-storage (k8s 1.19+) o quay.io/k8scsi" 


| `kubeletDir` | Percorso della directory del kubelet sull'host | "/var/lib/kubelet" 


| `wipeout` | Un elenco di risorse da eliminare per eseguire una rimozione completa di Astra Trident |  


| `imagePullSecrets` | Secrets (segreti) per estrarre immagini da un registro interno |  


| `controllerPluginNodeSelector` | Selettori di nodi aggiuntivi per i pod che eseguono il Plugin CSI del controller Trident. Segue lo stesso formato di pod.spec.nodeSelector. | Nessuna impostazione predefinita; opzionale 


| `controllerPluginTolerations` | Ignora le tolleranze per i pod che eseguono il Plugin CSI del controller Trident. Segue lo stesso formato di pod.spec.Tolerations. | Nessuna impostazione predefinita; opzionale 


| `nodePluginNodeSelector` | Selettori di nodi aggiuntivi per i pod che eseguono il Plugin CSI di Trident Node. Segue lo stesso formato di pod.spec.nodeSelector. | Nessuna impostazione predefinita; opzionale 


| `nodePluginTolerations` | Ignora le tolleranze per i pod che eseguono il Plugin CSI di Trident Node. Segue lo stesso formato di pod.spec.Tolerations. | Nessuna impostazione predefinita; opzionale 
|===

IMPORTANT: `spec.namespace` è specificato in `TridentOrchestrator` Per indicare in quale spazio dei nomi Astra Trident è installato. Questo parametro *non può essere aggiornato dopo l'installazione di Astra Trident*. Il tentativo di eseguire questa operazione causa lo stato di `TridentOrchestrator` per passare a. `Failed`. Astra Trident non deve essere migrato tra spazi dei nomi.


TIP: Per ulteriori informazioni sulla formattazione dei parametri del pod, vedere link:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/["Assegnazione di pod ai nodi"^].

È possibile utilizzare gli attributi menzionati in precedenza per la definizione `TridentOrchestrator` per personalizzare l'installazione. Ecco un esempio:

[listing]
----
cat deploy/crds/tridentorchestrator_cr_imagepullsecrets.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullSecrets:
  - thisisasecret
----
Ecco un altro esempio che mostra come Trident può essere implementato con i selettori di nodo:

[listing]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  controllerPluginNodeSelector:
    nodetype: master
  nodePluginNodeSelector:
    storage: netapp
----
Se si desidera personalizzare l'installazione oltre ciò che si desidera `TridentOrchestrator` gli argomenti lo consentono, dovresti considerare di utilizzare `tridentctl` Per generare manifesti YAML personalizzati che è possibile modificare in base alle esigenze.
